apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - image: lewiscontato99/hellok8s:v1
        name: hellok8s-container
        ports:
        - containerPort: 4567  # Expose port 4567
